version: '3'
volumes:
  pg_data:
  static:


services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: wadss07/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: wadss07/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: wadss07/taski_gateway
    volumes:
      - static_volume:/staticfiles/
    depends_on:
      - backend
    ports:
      - 8000:80
